@base = http://localhost:3000
@productAPI = api/v1/products

GET {{base}}/{{productAPI}}

### get product sort 
GET {{base}}/{{productAPI}}?featured=true&sort=-name,company

### get product field
GET {{base}}/{{productAPI}}?featured=true&sort=-name,company&fields=name

### get all product field without filter
GET {{base}}/{{productAPI}}?fields=name

### get product static
GET {{base}}/{{productAPI}}


### create product
POST {{base}}/{{productAPI}}
Content-Type: application/json

{
    "name": "t-shirt",
    "price": 5000, 
    "featured": true, 
    "rating": 3.5,
    "company": "caressa"
}


### get all products
GET {{base}}/{{productAPI}}

### delete a product
DELETE {{base}}/{{productAPI}}/6942adbbecb850215cb98888


### get a product 
GET {{base}}/{{productAPI}}/69427b28cd3ce94bfc774599

### update a product
PATCH {{base}}/{{productAPI}}/6942adbbecb850215cb98888
Content-Type: application/json

{
    "name": "t-shirt ",
    "price": 90
}