@baseTaskUrl = http://localhost:3000/api/v1/tasks/


### get all tasks
GET {{baseTaskUrl}}


### get a task
GET {{baseTaskUrl}}/69400da8b69c2b0f00666b5a



### create task
POST {{baseTaskUrl}}
Content-Type: application/json

{
    "name": "Task name ii",
    "completed": true
}


### delete task 
DELETE {{baseTaskUrl}}/6941e2e16b2af6264071dba3

### update task
PATCH {{baseTaskUrl}}/69400da8b69c2b0f00666b5a
Content-Type: application/json

{
    "name": "Task name"
}


